# Generated by Django 4.2.7 on 2023-12-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bike",
            name="brand",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="bike",
            name="rent_price",
            field=models.IntegerField(default=0),
        ),
    ]
