# Generated by Django 4.2.7 on 2023-12-21 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_delete_rentee_rentee_alter_renteeprofile_user"),
        ("components", "0003_rename_event_type_history_rental_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="Bike",
            name="rented_by",
            field=models.ManyToManyField(
                related_name="bike_reentee", to="users.rentee"
            ),
        ),
        migrations.AlterField(
            model_name="History",
            name="rentee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rentee_history",
                to="users.rentee",
            ),
        ),
    ]
