# Generated by Django 4.2.7 on 2023-11-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_is_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="renteeprofile",
            old_name="renter_id",
            new_name="rentee_id",
        ),
        migrations.AlterField(
            model_name="renteeprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="users.rentee"
            ),
        ),
        migrations.AlterField(
            model_name="renterprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="users.renter"
            ),
        ),
    ]
