# Generated by Django 4.2.7 on 2023-12-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_administrator_joined_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="renteeprofile",
            name="rentee_id",
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="renterprofile",
            name="renter_id",
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
