# Generated by Django 4.2.7 on 2023-12-21 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Rentee",
        ),
        migrations.CreateModel(
            name="Rentee",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("users.user",),
            managers=[
                ("Rentee", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="RenteeProfile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="users.rentee"
            ),
        ),
    ]
